apiVersion: cronhpa.tomoku.com/v1
kind: CronHPA
metadata:
  annotations:
    cronhpa.tomoku.github.com/skip: "false"
  name: cronhpa-test1
  namespace: default
spec:
  template:
    spec:
      behavior:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: ngnix-mudu
      minReplicas: 2
      maxReplicas: 3
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
  cronPatches:
  - name: daytime
    schedule: "30 * * * *"
    timezone: "Asia/Tokyo"
    patch:
      minReplicas: 1
  - name: "nighttime"
    schedule: "10 * * * *"
    timezone: "Asia/Tokyo"
    patch:
      minReplicas: 3
      maxReplicas: 3
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 70
