apiVersion: cronhpa.tomoku.com/v1
kind: CronHPA
metadata:
  name: cronhpa-test1
  namespace: default
spec:
  template:
    spec:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 1800
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: ngnix-mudu
      minReplicas: 2
      maxReplicas: 3
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 60
  cron:
  - name: "daytime"
    schedule: "0 7 0 0 1-5"
    timezone: "Asia/China"
    minReplicas: 2
    maxReplicas: 3
