---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cronhpa.tomoku.com
  resources:
  - cronhpas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cronhpa.tomoku.com
  resources:
  - cronhpas/finalizers
  verbs:
  - update
- apiGroups:
  - cronhpa.tomoku.com
  resources:
  - cronhpas/status
  verbs:
  - get
  - patch
  - update
